{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "0f00a99a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Package                            Version\n",
      "---------------------------------- -------------------\n",
      "absl-py                            1.0.0\n",
      "aiobotocore                        1.2.1\n",
      "aiohttp                            3.8.1\n",
      "aioitertools                       0.7.1\n",
      "aiosignal                          1.2.0\n",
      "alabaster                          0.7.12\n",
      "anaconda-client                    1.7.2\n",
      "anaconda-project                   0.9.1\n",
      "anyio                              2.1.0\n",
      "appdirs                            1.4.4\n",
      "argh                               0.26.2\n",
      "argon2-cffi                        20.1.0\n",
      "asn1crypto                         1.4.0\n",
      "astroid                            2.9.3\n",
      "astropy                            4.1\n",
      "astunparse                         1.6.3\n",
      "async-generator                    1.10\n",
      "async-timeout                      4.0.2\n",
      "asynctest                          0.13.0\n",
      "atomicwrites                       1.4.0\n",
      "attrs                              20.3.0\n",
      "autopep8                           1.5.5\n",
      "autovizwidget                      0.19.1\n",
      "awscli                             1.24.10\n",
      "Babel                              2.9.1\n",
      "backcall                           0.2.0\n",
      "backports.functools-lru-cache      1.6.1\n",
      "backports.shutil-get-terminal-size 1.0.0\n",
      "bcrypt                             4.0.0\n",
      "beautifulsoup4                     4.9.3\n",
      "bitarray                           1.6.3\n",
      "bkcharts                           0.2\n",
      "black                              20.8b1\n",
      "blaze                              0.11.3\n",
      "bleach                             4.1.0\n",
      "bokeh                              2.3.3\n",
      "boto                               2.49.0\n",
      "boto3                              1.23.10\n",
      "botocore                           1.26.10\n",
      "Bottleneck                         1.3.2\n",
      "brotlipy                           0.7.0\n",
      "cached-property                    1.5.1\n",
      "cachetools                         4.2.4\n",
      "certifi                            2021.5.30\n",
      "cffi                               1.14.5\n",
      "chardet                            3.0.4\n",
      "charset-normalizer                 2.0.12\n",
      "click                              7.1.2\n",
      "cloudpickle                        1.6.0\n",
      "clyent                             1.2.2\n",
      "colorama                           0.4.3\n",
      "contextlib2                        0.6.0.post1\n",
      "contextvars                        2.4\n",
      "coverage                           6.2\n",
      "cryptography                       3.4.4\n",
      "cycler                             0.10.0\n",
      "Cython                             0.29.22\n",
      "cytoolz                            0.11.0\n",
      "dask                               2021.2.0\n",
      "dataclasses                        0.8\n",
      "datashape                          0.5.4\n",
      "decorator                          4.4.2\n",
      "defusedxml                         0.6.0\n",
      "diff-match-patch                   20200713\n",
      "dill                               0.3.4\n",
      "distributed                        2021.2.0\n",
      "distro                             1.7.0\n",
      "docker                             5.0.3\n",
      "docker-compose                     1.29.2\n",
      "dockerpty                          0.4.1\n",
      "docopt                             0.6.2\n",
      "docutils                           0.15.2\n",
      "dparse                             0.5.1\n",
      "ei-for-tf                          1.6.0\n",
      "entrypoints                        0.3\n",
      "environment-kernels                1.1.1\n",
      "et-xmlfile                         1.0.1\n",
      "fastcache                          1.1.0\n",
      "filelock                           3.0.12\n",
      "flake8                             3.8.4\n",
      "Flask                              1.1.2\n",
      "Flask-Cors                         3.0.10\n",
      "frozenlist                         1.2.0\n",
      "fsspec                             0.8.7\n",
      "future                             0.18.2\n",
      "gast                               0.3.3\n",
      "gevent                             21.1.2\n",
      "glob2                              0.7\n",
      "gmpy2                              2.1.0b1\n",
      "google-auth                        2.6.2\n",
      "google-auth-oauthlib               0.4.6\n",
      "google-pasta                       0.2.0\n",
      "greenlet                           0.4.17\n",
      "grpcio                             1.44.0\n",
      "gssapi                             1.7.3\n",
      "h5py                               2.10.0\n",
      "hdijupyterutils                    0.19.1\n",
      "HeapDict                           1.0.1\n",
      "helpdev                            0.7.1\n",
      "html5lib                           1.1\n",
      "idna                               3.1\n",
      "idna-ssl                           1.1.0\n",
      "imageio                            2.9.0\n",
      "imagesize                          1.2.0\n",
      "immutables                         0.15\n",
      "importlib-metadata                 4.8.3\n",
      "importlib-resources                5.4.0\n",
      "iniconfig                          1.1.1\n",
      "intervaltree                       3.0.2\n",
      "ipykernel                          5.5.0\n",
      "ipyparallel                        6.3.0\n",
      "ipython                            7.16.1\n",
      "ipython-genutils                   0.2.0\n",
      "ipywidgets                         7.6.3\n",
      "isort                              5.7.0\n",
      "itsdangerous                       1.1.0\n",
      "jdcal                              1.4.1\n",
      "jedi                               0.17.2\n",
      "jeepney                            0.6.0\n",
      "Jinja2                             2.11.3\n",
      "jmespath                           0.10.0\n",
      "joblib                             1.0.1\n",
      "json5                              0.9.5\n",
      "jsonschema                         3.2.0\n",
      "jupyter                            1.0.0\n",
      "jupyter-client                     7.1.2\n",
      "jupyter-console                    6.4.3\n",
      "jupyter-core                       4.7.1\n",
      "jupyter-packaging                  0.7.12\n",
      "jupyter-server                     1.4.1\n",
      "jupyterlab                         3.2.9\n",
      "jupyterlab-launcher                0.13.1\n",
      "jupyterlab-pygments                0.1.2\n",
      "jupyterlab-server                  2.3.0\n",
      "jupyterlab-widgets                 1.0.0\n",
      "Keras                              2.4.3\n",
      "Keras-Preprocessing                1.1.2\n",
      "keyring                            22.0.1\n",
      "kiwisolver                         1.3.1\n",
      "krb5                               0.3.0\n",
      "lazy-object-proxy                  1.5.2\n",
      "llvmlite                           0.35.0\n",
      "locket                             0.2.0\n",
      "lxml                               4.8.0\n",
      "Markdown                           3.3.6\n",
      "MarkupSafe                         1.1.1\n",
      "matplotlib                         3.3.4\n",
      "mccabe                             0.6.1\n",
      "mistune                            0.8.4\n",
      "mkl-service                        2.3.0\n",
      "mock                               4.0.3\n",
      "more-itertools                     8.7.0\n",
      "mpmath                             1.2.1\n",
      "msgpack                            1.0.2\n",
      "multidict                          5.1.0\n",
      "multipledispatch                   0.6.0\n",
      "multiprocess                       0.70.12.2\n",
      "mypy-extensions                    0.4.3\n",
      "nb-conda                           2.2.1\n",
      "nb-conda-kernels                   2.3.1\n",
      "nbclassic                          0.2.6\n",
      "nbclient                           0.5.2\n",
      "nbconvert                          6.0.7\n",
      "nbformat                           5.1.2\n",
      "nest-asyncio                       1.5.4\n",
      "networkx                           2.5\n",
      "nltk                               3.6.7\n",
      "nose                               1.3.7\n",
      "notebook                           6.4.10\n",
      "numba                              0.52.0\n",
      "numexpr                            2.7.2\n",
      "numpy                              1.19.5\n",
      "numpydoc                           1.1.0\n",
      "oauthlib                           3.2.0\n",
      "odo                                0.5.1\n",
      "olefile                            0.46\n",
      "opencv-python                      4.2.0.34\n",
      "openpyxl                           3.0.6\n",
      "opt-einsum                         3.3.0\n",
      "packaging                          21.3\n",
      "pandas                             1.1.5\n",
      "pandocfilters                      1.4.2\n",
      "paramiko                           2.11.0\n",
      "parso                              0.7.0\n",
      "partd                              1.1.0\n",
      "path                               15.1.2\n",
      "pathlib2                           2.3.5\n",
      "pathos                             0.2.8\n",
      "pathspec                           0.8.1\n",
      "patsy                              0.5.1\n",
      "pep8                               1.7.1\n",
      "pexpect                            4.8.0\n",
      "pickleshare                        0.7.5\n",
      "Pillow                             8.4.0\n",
      "pip                                21.3.1\n",
      "pkginfo                            1.7.0\n",
      "platformdirs                       2.4.0\n",
      "plotly                             5.6.0\n",
      "pluggy                             0.13.1\n",
      "ply                                3.11\n",
      "pox                                0.3.0\n",
      "ppft                               1.6.6.4\n",
      "prometheus-client                  0.9.0\n",
      "prompt-toolkit                     3.0.4\n",
      "protobuf                           3.15.1\n",
      "protobuf3-to-dict                  0.1.5\n",
      "psutil                             5.8.0\n",
      "psycopg2-binary                    2.9.3\n",
      "ptyprocess                         0.7.0\n",
      "py                                 1.10.0\n",
      "py4j                               0.10.7\n",
      "pyasn1                             0.4.8\n",
      "pyasn1-modules                     0.2.8\n",
      "pycodestyle                        2.6.0\n",
      "pycosat                            0.6.3\n",
      "pycparser                          2.20\n",
      "pycrypto                           2.6.1\n",
      "pycurl                             7.43.0.6\n",
      "pydocstyle                         5.1.1\n",
      "pyflakes                           2.2.0\n",
      "pygal                              2.4.0\n",
      "Pygments                           2.8.0\n",
      "pyinstrument                       3.4.2\n",
      "pyinstrument-cext                  0.2.4\n",
      "pykerberos                         1.2.1\n",
      "pylint                             2.12.2\n",
      "pyls-black                         0.4.6\n",
      "pyls-spyder                        0.3.2\n",
      "PyNaCl                             1.5.0\n",
      "pyodbc                             4.0.30\n",
      "pyOpenSSL                          20.0.1\n",
      "pyparsing                          2.4.7\n",
      "PyQt5                              5.12.3\n",
      "PyQt5_sip                          4.19.18\n",
      "PyQtChart                          5.12\n",
      "PyQtWebEngine                      5.12.1\n",
      "pyrsistent                         0.17.3\n",
      "PySocks                            1.7.1\n",
      "pyspark                            2.4.0\n",
      "pyspnego                           0.5.0\n",
      "pytest                             6.2.2\n",
      "python-dateutil                    2.8.1\n",
      "python-dotenv                      0.20.0\n",
      "python-jsonrpc-server              0.4.0\n",
      "python-language-server             0.36.2\n",
      "pytz                               2021.1\n",
      "PyWavelets                         1.1.1\n",
      "pyxdg                              0.26\n",
      "PyYAML                             5.4.1\n",
      "pyzmq                              22.0.3\n",
      "QDarkStyle                         2.8.1\n",
      "QtAwesome                          1.0.2\n",
      "qtconsole                          5.0.2\n",
      "QtPy                               1.9.0\n",
      "regex                              2022.3.15\n",
      "requests                           2.27.1\n",
      "requests-kerberos                  0.14.0\n",
      "requests-oauthlib                  1.3.1\n",
      "rope                               0.18.0\n",
      "rsa                                4.7.2\n",
      "Rtree                              0.9.7\n",
      "ruamel-yaml-conda                  0.15.80\n",
      "s3fs                               0.5.2\n",
      "s3transfer                         0.5.2\n",
      "safety                             1.10.3\n",
      "sagemaker                          2.109.0\n",
      "sagemaker-pyspark                  1.4.2\n",
      "scikit-image                       0.16.2\n",
      "scikit-learn                       0.24.1\n",
      "scipy                              1.5.3\n",
      "seaborn                            0.11.1\n",
      "SecretStorage                      3.3.1\n",
      "Send2Trash                         1.8.0\n",
      "setuptools                         49.6.0.post20210108\n",
      "shap                               0.40.0\n",
      "simplegeneric                      0.8.1\n",
      "singledispatch                     0.0.0\n",
      "sip                                4.19.24\n",
      "six                                1.15.0\n",
      "slicer                             0.0.7\n",
      "smdebug                            1.0.12\n",
      "smdebug-rulesconfig                1.0.1\n",
      "sniffio                            1.2.0\n",
      "snowballstemmer                    2.1.0\n",
      "sortedcollections                  2.1.0\n",
      "sortedcontainers                   2.3.0\n",
      "soupsieve                          2.0.1\n",
      "sparkmagic                         0.15.0\n",
      "Sphinx                             3.5.1\n",
      "sphinxcontrib-applehelp            1.0.2\n",
      "sphinxcontrib-devhelp              1.0.2\n",
      "sphinxcontrib-htmlhelp             1.0.3\n",
      "sphinxcontrib-jsmath               1.0.1\n",
      "sphinxcontrib-qthelp               1.0.3\n",
      "sphinxcontrib-serializinghtml      1.1.4\n",
      "sphinxcontrib-websupport           1.2.4\n",
      "spyder                             4.2.0\n",
      "spyder-kernels                     1.10.0\n",
      "SQLAlchemy                         1.3.23\n",
      "statsmodels                        0.12.2\n",
      "sympy                              1.7.1\n",
      "tables                             3.6.1\n",
      "tblib                              1.6.0\n",
      "tenacity                           8.0.1\n",
      "tensorboard                        2.8.0\n",
      "tensorboard-data-server            0.6.1\n",
      "tensorboard-plugin-wit             1.8.1\n",
      "tensorflow                         2.3.4\n",
      "tensorflow-estimator               2.3.0\n",
      "tensorflow-serving-api             2.3.0\n",
      "termcolor                          1.1.0\n",
      "terminado                          0.9.2\n",
      "testpath                           0.4.4\n",
      "texttable                          1.6.4\n",
      "threadpoolctl                      2.1.0\n",
      "three-merge                        0.1.1\n",
      "toml                               0.10.2\n",
      "toolz                              0.11.1\n",
      "tornado                            6.1\n",
      "tqdm                               4.63.0\n",
      "traitlets                          4.3.3\n",
      "typed-ast                          1.4.2\n",
      "typing_extensions                  4.1.1\n",
      "ujson                              4.0.2\n",
      "unicodecsv                         0.14.1\n",
      "urllib3                            1.26.8\n",
      "watchdog                           2.0.2\n",
      "wcwidth                            0.2.5\n",
      "webencodings                       0.5.1\n",
      "websocket-client                   0.59.0\n",
      "Werkzeug                           2.0.3\n",
      "wheel                              0.36.2\n",
      "widgetsnbextension                 3.5.1\n",
      "wrapt                              1.12.1\n",
      "wurlitzer                          2.0.1\n",
      "xlrd                               2.0.1\n",
      "XlsxWriter                         1.3.7\n",
      "xlwt                               1.3.0\n",
      "yapf                               0.30.0\n",
      "yarl                               1.6.3\n",
      "zict                               2.0.0\n",
      "zipp                               3.4.0\n",
      "zope.event                         4.5.0\n",
      "zope.interface                     5.2.0\n"
     ]
    }
   ],
   "source": [
    "!pip list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "a5f40b9b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Looking in indexes: https://pypi.org/simple, https://pip.repos.neuron.amazonaws.com\n",
      "Requirement already satisfied: mlflow in /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages (1.23.1)\n",
      "Requirement already satisfied: pymysql in /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages (1.0.2)\n",
      "Requirement already satisfied: boto3 in /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages (1.23.10)\n",
      "Collecting mysql\n",
      "  Downloading mysql-0.0.3-py3-none-any.whl (1.2 kB)\n",
      "Requirement already satisfied: alembic in /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages (from mlflow) (1.7.7)\n",
      "Requirement already satisfied: databricks-cli>=0.8.7 in /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages (from mlflow) (0.17.3)\n",
      "Requirement already satisfied: requests>=2.17.3 in /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages (from mlflow) (2.27.1)\n",
      "Requirement already satisfied: gitpython>=2.1.0 in /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages (from mlflow) (3.1.18)\n",
      "Requirement already satisfied: entrypoints in /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages (from mlflow) (0.3)\n",
      "Requirement already satisfied: gunicorn in /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages (from mlflow) (20.1.0)\n",
      "Requirement already satisfied: sqlparse>=0.3.1 in /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages (from mlflow) (0.4.3)\n",
      "Requirement already satisfied: protobuf>=3.7.0 in /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages (from mlflow) (3.15.1)\n",
      "Requirement already satisfied: click>=7.0 in /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages (from mlflow) (7.1.2)\n",
      "Requirement already satisfied: numpy in /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages (from mlflow) (1.19.5)\n",
      "Requirement already satisfied: sqlalchemy in /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages (from mlflow) (1.3.23)\n",
      "Requirement already satisfied: scipy in /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages (from mlflow) (1.5.3)\n",
      "Requirement already satisfied: pyyaml>=5.1 in /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages (from mlflow) (5.4.1)\n",
      "Requirement already satisfied: prometheus-flask-exporter in /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages (from mlflow) (0.20.3)\n",
      "Requirement already satisfied: importlib-metadata!=4.7.0,>=3.7.0 in /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages (from mlflow) (4.8.3)\n",
      "Requirement already satisfied: cloudpickle in /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages (from mlflow) (1.6.0)\n",
      "Requirement already satisfied: packaging in /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages (from mlflow) (21.3)\n",
      "Requirement already satisfied: querystring-parser in /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages (from mlflow) (1.2.4)\n",
      "Requirement already satisfied: pandas in /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages (from mlflow) (1.1.5)\n",
      "Requirement already satisfied: docker>=4.0.0 in /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages (from mlflow) (5.0.3)\n",
      "Requirement already satisfied: pytz in /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages (from mlflow) (2021.1)\n",
      "Requirement already satisfied: Flask in /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages (from mlflow) (1.1.2)\n",
      "Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages (from boto3) (0.10.0)\n",
      "Requirement already satisfied: botocore<1.27.0,>=1.26.10 in /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages (from boto3) (1.26.10)\n",
      "Requirement already satisfied: s3transfer<0.6.0,>=0.5.0 in /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages (from boto3) (0.5.2)\n",
      "Collecting mysqlclient\n",
      "  Downloading mysqlclient-2.1.1.tar.gz (88 kB)\n",
      "     |████████████████████████████████| 88 kB 10.2 MB/s            \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_264823ae8fa345a194509b7be7b7f732/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_264823ae8fa345a194509b7be7b7f732/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-e76qi_9j\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysqlclient_264823ae8fa345a194509b7be7b7f732/\n",
      "  Complete output (15 lines):\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  /bin/sh: mariadb_config: command not found\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  mysql_config --version\n",
      "  mariadb_config --version\n",
      "  mysql_config --libs\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_264823ae8fa345a194509b7be7b7f732/setup.py\", line 15, in <module>\n",
      "      metadata, options = get_config()\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_264823ae8fa345a194509b7be7b7f732/setup_posix.py\", line 70, in get_config\n",
      "      libs = mysql_config(\"libs\")\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_264823ae8fa345a194509b7be7b7f732/setup_posix.py\", line 31, in mysql_config\n",
      "      raise OSError(\"{} not found\".format(_mysql_config_path))\n",
      "  OSError: mysql_config not found\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/50/5f/eac919b88b9df39bbe4a855f136d58f80d191cfea34a3dcf96bf5d8ace0a/mysqlclient-2.1.1.tar.gz#sha256=828757e419fb11dd6c5ed2576ec92c3efaa93a0f7c39e263586d1ee779c3d782 (from https://pypi.org/simple/mysqlclient/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-2.1.0.tar.gz (87 kB)\n",
      "     |████████████████████████████████| 87 kB 12.9 MB/s            \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_15ecda20f7bf4176a9f508eba53a9671/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_15ecda20f7bf4176a9f508eba53a9671/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-kcxrfbeu\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysqlclient_15ecda20f7bf4176a9f508eba53a9671/\n",
      "  Complete output (15 lines):\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  /bin/sh: mariadb_config: command not found\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  mysql_config --version\n",
      "  mariadb_config --version\n",
      "  mysql_config --libs\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_15ecda20f7bf4176a9f508eba53a9671/setup.py\", line 15, in <module>\n",
      "      metadata, options = get_config()\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_15ecda20f7bf4176a9f508eba53a9671/setup_posix.py\", line 70, in get_config\n",
      "      libs = mysql_config(\"libs\")\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_15ecda20f7bf4176a9f508eba53a9671/setup_posix.py\", line 31, in mysql_config\n",
      "      raise OSError(\"{} not found\".format(_mysql_config_path))\n",
      "  OSError: mysql_config not found\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/de/79/d02be3cb942afda6c99ca207858847572e38146eb73a7c4bfe3bdf154626/mysqlclient-2.1.0.tar.gz#sha256=973235686f1b720536d417bf0a0d39b4ab3d5086b2b6ad5e6752393428c02b12 (from https://pypi.org/simple/mysqlclient/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-2.0.3.tar.gz (88 kB)\n",
      "     |████████████████████████████████| 88 kB 16.0 MB/s            \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_c93319ff201a4a65975dfe01dc9bad30/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_c93319ff201a4a65975dfe01dc9bad30/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-0gcr8pn1\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysqlclient_c93319ff201a4a65975dfe01dc9bad30/\n",
      "  Complete output (15 lines):\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  /bin/sh: mariadb_config: command not found\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  mysql_config --version\n",
      "  mariadb_config --version\n",
      "  mysql_config --libs\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_c93319ff201a4a65975dfe01dc9bad30/setup.py\", line 15, in <module>\n",
      "      metadata, options = get_config()\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_c93319ff201a4a65975dfe01dc9bad30/setup_posix.py\", line 70, in get_config\n",
      "      libs = mysql_config(\"libs\")\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_c93319ff201a4a65975dfe01dc9bad30/setup_posix.py\", line 31, in mysql_config\n",
      "      raise OSError(\"{} not found\".format(_mysql_config_path))\n",
      "  OSError: mysql_config not found\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/3c/df/59cd2fa5e48d0804d213bdcb1acb4d08c403b61c7ff7ed4dd4a6a2deb3f7/mysqlclient-2.0.3.tar.gz#sha256=f6ebea7c008f155baeefe16c56cd3ee6239f7a5a9ae42396c2f1860f08a7c432 (from https://pypi.org/simple/mysqlclient/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-2.0.2.tar.gz (88 kB)\n",
      "     |████████████████████████████████| 88 kB 15.8 MB/s            \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_3c733524596a48ba9e253e0fb0fb0697/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_3c733524596a48ba9e253e0fb0fb0697/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-njja9dwt\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysqlclient_3c733524596a48ba9e253e0fb0fb0697/\n",
      "  Complete output (12 lines):\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  /bin/sh: mariadb_config: command not found\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_3c733524596a48ba9e253e0fb0fb0697/setup.py\", line 15, in <module>\n",
      "      metadata, options = get_config()\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_3c733524596a48ba9e253e0fb0fb0697/setup_posix.py\", line 65, in get_config\n",
      "      libs = mysql_config(\"libs\")\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_3c733524596a48ba9e253e0fb0fb0697/setup_posix.py\", line 31, in mysql_config\n",
      "      raise OSError(\"{} not found\".format(_mysql_config_path))\n",
      "  OSError: mysql_config not found\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/0e/68/f79de0e0fcdb041783124b825771e0ba6a3d0893b7b4c4735f130e42af47/mysqlclient-2.0.2.tar.gz#sha256=8df057b08fc27d8f7106bfa997d0a21e2acef017f905f06d6fb0aa6a20d4d2b2 (from https://pypi.org/simple/mysqlclient/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-2.0.1.tar.gz (87 kB)\n",
      "     |████████████████████████████████| 87 kB 15.1 MB/s            \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_c046959d7eb34f36a118f023feddbfe5/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_c046959d7eb34f36a118f023feddbfe5/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-91dtq47p\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysqlclient_c046959d7eb34f36a118f023feddbfe5/\n",
      "  Complete output (12 lines):\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  /bin/sh: mariadb_config: command not found\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_c046959d7eb34f36a118f023feddbfe5/setup.py\", line 15, in <module>\n",
      "      metadata, options = get_config()\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_c046959d7eb34f36a118f023feddbfe5/setup_posix.py\", line 65, in get_config\n",
      "      libs = mysql_config(\"libs\")\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_c046959d7eb34f36a118f023feddbfe5/setup_posix.py\", line 31, in mysql_config\n",
      "      raise OSError(\"{} not found\".format(_mysql_config_path))\n",
      "  OSError: mysql_config not found\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/a5/e1/e5f2b231c05dc51d9d87fa5066f90d1405345c54b14b0b11a1c859020f21/mysqlclient-2.0.1.tar.gz#sha256=fb2f75aea14722390d2d8ddf384ad99da708c707a96656210a7be8af20a2c5e5 (from https://pypi.org/simple/mysqlclient/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-2.0.0.tar.gz (87 kB)\n",
      "     |████████████████████████████████| 87 kB 760 kB/s             \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_92ddb30cb17d46408dd6343620c4f3b0/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_92ddb30cb17d46408dd6343620c4f3b0/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1cgrp25i\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysqlclient_92ddb30cb17d46408dd6343620c4f3b0/\n",
      "  Complete output (12 lines):\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  /bin/sh: mariadb_config: command not found\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_92ddb30cb17d46408dd6343620c4f3b0/setup.py\", line 15, in <module>\n",
      "      metadata, options = get_config()\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_92ddb30cb17d46408dd6343620c4f3b0/setup_posix.py\", line 65, in get_config\n",
      "      libs = mysql_config(\"libs\")\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_92ddb30cb17d46408dd6343620c4f3b0/setup_posix.py\", line 31, in mysql_config\n",
      "      raise OSError(\"{} not found\".format(_mysql_config_path))\n",
      "  OSError: mysql_config not found\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/ca/cf/dd8124bf8b3d2ae465db9c8ce35c51650c31784b095f41faf6f8cad987a0/mysqlclient-2.0.0.tar.gz#sha256=201dfcc2a3c8a0859ea399947f1af8abe74b706beba0ebac149180d9d7b0f6e8 (from https://pypi.org/simple/mysqlclient/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.4.6.tar.gz (85 kB)\n",
      "     |████████████████████████████████| 85 kB 7.8 MB/s             \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_a37f85d1b6304a9fae5bc786f0f87745/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_a37f85d1b6304a9fae5bc786f0f87745/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-yu60syb4\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysqlclient_a37f85d1b6304a9fae5bc786f0f87745/\n",
      "  Complete output (12 lines):\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  /bin/sh: mariadb_config: command not found\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_a37f85d1b6304a9fae5bc786f0f87745/setup.py\", line 16, in <module>\n",
      "      metadata, options = get_config()\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_a37f85d1b6304a9fae5bc786f0f87745/setup_posix.py\", line 61, in get_config\n",
      "      libs = mysql_config(\"libs\")\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_a37f85d1b6304a9fae5bc786f0f87745/setup_posix.py\", line 29, in mysql_config\n",
      "      raise EnvironmentError(\"%s not found\" % (_mysql_config_path,))\n",
      "  OSError: mysql_config not found\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/d0/97/7326248ac8d5049968bf4ec708a5d3d4806e412a42e74160d7f266a3e03a/mysqlclient-1.4.6.tar.gz#sha256=f3fdaa9a38752a3b214a6fe79d7cae3653731a53e577821f9187e67cbecb2e16 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.4.5.tar.gz (86 kB)\n",
      "     |████████████████████████████████| 86 kB 840 kB/s             \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_0213769afcd447978f5c01978af6d2d4/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_0213769afcd447978f5c01978af6d2d4/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ts8qdyt8\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysqlclient_0213769afcd447978f5c01978af6d2d4/\n",
      "  Complete output (12 lines):\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  /bin/sh: mariadb_config: command not found\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_0213769afcd447978f5c01978af6d2d4/setup.py\", line 16, in <module>\n",
      "      metadata, options = get_config()\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_0213769afcd447978f5c01978af6d2d4/setup_posix.py\", line 61, in get_config\n",
      "      libs = mysql_config(\"libs\")\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_0213769afcd447978f5c01978af6d2d4/setup_posix.py\", line 29, in mysql_config\n",
      "      raise EnvironmentError(\"%s not found\" % (_mysql_config_path,))\n",
      "  OSError: mysql_config not found\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/f8/9b/5db9a03e2088a87c26e3e4d4c7f7e8f4c2dbae610f9521cdfac15755a795/mysqlclient-1.4.5.tar.gz#sha256=e80109b0ae8d952b900b31b623181532e5e89376d707dcbeb63f99e69cefe559 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.4.4.tar.gz (86 kB)\n",
      "     |████████████████████████████████| 86 kB 705 kB/s             \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_d80edabb39204c83a08ae2b35058c275/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_d80edabb39204c83a08ae2b35058c275/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-b45h76hw\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysqlclient_d80edabb39204c83a08ae2b35058c275/\n",
      "  Complete output (12 lines):\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  /bin/sh: mariadb_config: command not found\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_d80edabb39204c83a08ae2b35058c275/setup.py\", line 16, in <module>\n",
      "      metadata, options = get_config()\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_d80edabb39204c83a08ae2b35058c275/setup_posix.py\", line 61, in get_config\n",
      "      libs = mysql_config(\"libs\")\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_d80edabb39204c83a08ae2b35058c275/setup_posix.py\", line 29, in mysql_config\n",
      "      raise EnvironmentError(\"%s not found\" % (_mysql_config_path,))\n",
      "  OSError: mysql_config not found\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/4d/38/c5f8bac9c50f3042c8f05615f84206f77f03db79781db841898fde1bb284/mysqlclient-1.4.4.tar.gz#sha256=9c737cc55a5dc8dd3583a942d5a9b21be58d16f00f5fefca4e575e7d9682e98c (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.4.3.tar.gz (86 kB)\n",
      "     |████████████████████████████████| 86 kB 9.5 MB/s             \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_345e53652722422fb2d7ffef8b328938/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_345e53652722422fb2d7ffef8b328938/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-drxew05z\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysqlclient_345e53652722422fb2d7ffef8b328938/\n",
      "  Complete output (12 lines):\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  /bin/sh: mariadb_config: command not found\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_345e53652722422fb2d7ffef8b328938/setup.py\", line 16, in <module>\n",
      "      metadata, options = get_config()\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_345e53652722422fb2d7ffef8b328938/setup_posix.py\", line 61, in get_config\n",
      "      libs = mysql_config(\"libs\")\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_345e53652722422fb2d7ffef8b328938/setup_posix.py\", line 29, in mysql_config\n",
      "      raise EnvironmentError(\"%s not found\" % (_mysql_config_path,))\n",
      "  OSError: mysql_config not found\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/13/37/6c941aabeb78464a538b7d43266bfae645993779e3ca3e12fe82b4590f52/mysqlclient-1.4.3.tar.gz#sha256=0d3eeb97534c9f42e9b65bd35c1a35fadc2f6d7ea5d9fdbda5339a569156344b (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.4.2.post1.tar.gz (85 kB)\n",
      "     |████████████████████████████████| 85 kB 8.3 MB/s             \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_c3387472947b455eb713fbc4caed0e4b/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_c3387472947b455eb713fbc4caed0e4b/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-0sp1r5vj\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysqlclient_c3387472947b455eb713fbc4caed0e4b/\n",
      "  Complete output (10 lines):\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_c3387472947b455eb713fbc4caed0e4b/setup.py\", line 16, in <module>\n",
      "      metadata, options = get_config()\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_c3387472947b455eb713fbc4caed0e4b/setup_posix.py\", line 51, in get_config\n",
      "      libs = mysql_config(\"libs\")\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_c3387472947b455eb713fbc4caed0e4b/setup_posix.py\", line 29, in mysql_config\n",
      "      raise EnvironmentError(\"%s not found\" % (_mysql_config_path,))\n",
      "  OSError: mysql_config not found\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/f4/f1/3bb6f64ca7a429729413e6556b7ba5976df06019a5245a43d36032f1061e/mysqlclient-1.4.2.post1.tar.gz#sha256=f257d250f2675d0ef99bd318906f3cfc05cef4a2f385ea695ff32a3f04b9f9a7 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.4.2.tar.gz (85 kB)\n",
      "     |████████████████████████████████| 85 kB 9.2 MB/s             \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_d93c7b87f0eb4fd29f5e7247f43f15d1/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_d93c7b87f0eb4fd29f5e7247f43f15d1/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-euvqxiux\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysqlclient_d93c7b87f0eb4fd29f5e7247f43f15d1/\n",
      "  Complete output (10 lines):\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_d93c7b87f0eb4fd29f5e7247f43f15d1/setup.py\", line 16, in <module>\n",
      "      metadata, options = get_config()\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_d93c7b87f0eb4fd29f5e7247f43f15d1/setup_posix.py\", line 51, in get_config\n",
      "      libs = mysql_config(\"libs\")\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_d93c7b87f0eb4fd29f5e7247f43f15d1/setup_posix.py\", line 29, in mysql_config\n",
      "      raise EnvironmentError(\"%s not found\" % (_mysql_config_path,))\n",
      "  OSError: mysql_config not found\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/73/79/67ddf24ac31b05d741f0ac87fa612c7a11bab1b39b8270ed7344d149f8af/mysqlclient-1.4.2.tar.gz#sha256=b95edaa41d6cc47deecabcdcbb5ab437ad9ae6d8955f5cf10d1847b37e66ef5e (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.4.1.tar.gz (85 kB)\n",
      "     |████████████████████████████████| 85 kB 392 kB/s             \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_ad93578187f84c17bb4628bb49d00adc/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_ad93578187f84c17bb4628bb49d00adc/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-o5t0a42c\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysqlclient_ad93578187f84c17bb4628bb49d00adc/\n",
      "  Complete output (10 lines):\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_ad93578187f84c17bb4628bb49d00adc/setup.py\", line 16, in <module>\n",
      "      metadata, options = get_config()\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_ad93578187f84c17bb4628bb49d00adc/setup_posix.py\", line 51, in get_config\n",
      "      libs = mysql_config(\"libs\")\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_ad93578187f84c17bb4628bb49d00adc/setup_posix.py\", line 29, in mysql_config\n",
      "      raise EnvironmentError(\"%s not found\" % (_mysql_config_path,))\n",
      "  OSError: mysql_config not found\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/de/d7/919042fb7ed78a89e21c4e43d5daed90d5df18ec183bae3de493a7d9e3ed/mysqlclient-1.4.1.tar.gz#sha256=a62220410e26ce2d2ff94dd0138c3ecfb91db634464a9afb4c8e6b50f0a67e00 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.4.0.tar.gz (85 kB)\n",
      "     |████████████████████████████████| 85 kB 2.9 MB/s             \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_672e1767fc8b40d4924172bcce48e0ad/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_672e1767fc8b40d4924172bcce48e0ad/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-m14jsjsv\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysqlclient_672e1767fc8b40d4924172bcce48e0ad/\n",
      "  Complete output (10 lines):\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_672e1767fc8b40d4924172bcce48e0ad/setup.py\", line 16, in <module>\n",
      "      metadata, options = get_config()\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_672e1767fc8b40d4924172bcce48e0ad/setup_posix.py\", line 51, in get_config\n",
      "      libs = mysql_config(\"libs\")\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_672e1767fc8b40d4924172bcce48e0ad/setup_posix.py\", line 29, in mysql_config\n",
      "      raise EnvironmentError(\"%s not found\" % (_mysql_config_path,))\n",
      "  OSError: mysql_config not found\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/05/73/fac741eef89b0257fb1807de80e96474f40d52739cdbc32c90c4a793e79d/mysqlclient-1.4.0.tar.gz#sha256=efeaacd04feea7d44fef2a5adf4df335b438458f8b89144307dc5a90025761a5 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.3.14.tar.gz (91 kB)\n",
      "     |████████████████████████████████| 91 kB 2.4 MB/s             \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_88b87ed541b949c6883e886625cb0485/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_88b87ed541b949c6883e886625cb0485/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_8wpqj3n\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysqlclient_88b87ed541b949c6883e886625cb0485/\n",
      "  Complete output (10 lines):\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_88b87ed541b949c6883e886625cb0485/setup.py\", line 16, in <module>\n",
      "      metadata, options = get_config()\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_88b87ed541b949c6883e886625cb0485/setup_posix.py\", line 53, in get_config\n",
      "      libs = mysql_config(\"libs_r\")\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_88b87ed541b949c6883e886625cb0485/setup_posix.py\", line 28, in mysql_config\n",
      "      raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "  OSError: mysql_config not found\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/f7/a2/1230ebbb4b91f42ad6b646e59eb8855559817ad5505d81c1ca2b5a216040/mysqlclient-1.3.14.tar.gz#sha256=3981ae9ce545901a36a8b7aed76ed02960a429f75dc53b7ad77fb2f9ab7cd56b (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.3.13.tar.gz (90 kB)\n",
      "     |████████████████████████████████| 90 kB 13.4 MB/s            \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_e71b6a6fc3cf4d6cba97d9a23e54406c/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_e71b6a6fc3cf4d6cba97d9a23e54406c/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-i04wjua8\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysqlclient_e71b6a6fc3cf4d6cba97d9a23e54406c/\n",
      "  Complete output (10 lines):\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_e71b6a6fc3cf4d6cba97d9a23e54406c/setup.py\", line 18, in <module>\n",
      "      metadata, options = get_config()\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_e71b6a6fc3cf4d6cba97d9a23e54406c/setup_posix.py\", line 53, in get_config\n",
      "      libs = mysql_config(\"libs_r\")\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_e71b6a6fc3cf4d6cba97d9a23e54406c/setup_posix.py\", line 28, in mysql_config\n",
      "      raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "  OSError: mysql_config not found\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/ec/fd/83329b9d3e14f7344d1cb31f128e6dbba70c5975c9e57896815dbb1988ad/mysqlclient-1.3.13.tar.gz#sha256=ff8ee1be84215e6c30a746b728c41eb0701a46ca76e343af445b35ce6250644f (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.3.12.tar.gz (89 kB)\n",
      "     |████████████████████████████████| 89 kB 11.8 MB/s            \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_1abcdc54623d415ca054444c4d199b17/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_1abcdc54623d415ca054444c4d199b17/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-udyw_u_f\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysqlclient_1abcdc54623d415ca054444c4d199b17/\n",
      "  Complete output (10 lines):\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_1abcdc54623d415ca054444c4d199b17/setup.py\", line 17, in <module>\n",
      "      metadata, options = get_config()\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_1abcdc54623d415ca054444c4d199b17/setup_posix.py\", line 44, in get_config\n",
      "      libs = mysql_config(\"libs_r\")\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_1abcdc54623d415ca054444c4d199b17/setup_posix.py\", line 26, in mysql_config\n",
      "      raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "  OSError: mysql_config not found\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/6f/86/bad31f1c1bb0cc99e88ca2adb7cb5c71f7a6540c1bb001480513de76a931/mysqlclient-1.3.12.tar.gz#sha256=2d9ec33de39f4d9c64ad7322ede0521d85829ce36a76f9dd3d6ab76a9c8648e5 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.3.11.tar.gz (89 kB)\n",
      "     |████████████████████████████████| 89 kB 16.3 MB/s            \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_5e0e82e4620d4b939ef147927dcdf8b4/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_5e0e82e4620d4b939ef147927dcdf8b4/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-7p0co25c\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysqlclient_5e0e82e4620d4b939ef147927dcdf8b4/\n",
      "  Complete output (10 lines):\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_5e0e82e4620d4b939ef147927dcdf8b4/setup.py\", line 17, in <module>\n",
      "      metadata, options = get_config()\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_5e0e82e4620d4b939ef147927dcdf8b4/setup_posix.py\", line 44, in get_config\n",
      "      libs = mysql_config(\"libs_r\")\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_5e0e82e4620d4b939ef147927dcdf8b4/setup_posix.py\", line 26, in mysql_config\n",
      "      raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "  OSError: mysql_config not found\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/6a/4d/856d1848e9b7fa8577a31c0188592f472e5cbc94f588c2a40ff930533d73/mysqlclient-1.3.11.tar.gz#sha256=9a79b38843d61f651266ff16b9fdcc8830d21f0fb852e4406a19e9a715bdf3e2 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.3.10.tar.gz (82 kB)\n",
      "     |████████████████████████████████| 82 kB 23 kB/s              \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_96b44ef936dc446d8bf62900a8e56d64/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_96b44ef936dc446d8bf62900a8e56d64/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-xbenh5tv\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysqlclient_96b44ef936dc446d8bf62900a8e56d64/\n",
      "  Complete output (10 lines):\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_96b44ef936dc446d8bf62900a8e56d64/setup.py\", line 17, in <module>\n",
      "      metadata, options = get_config()\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_96b44ef936dc446d8bf62900a8e56d64/setup_posix.py\", line 44, in get_config\n",
      "      libs = mysql_config(\"libs_r\")\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_96b44ef936dc446d8bf62900a8e56d64/setup_posix.py\", line 26, in mysql_config\n",
      "      raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "  OSError: mysql_config not found\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/40/9b/0bc869f290b8f49a99b8d97927f57126a5d1befcf8bac92c60dc855f2523/mysqlclient-1.3.10.tar.gz#sha256=452aaf9d2ba1a4fb85c134c88f9b1857852deed63b3b13255d7a65d2c1297262 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.3.9.tar.gz (81 kB)\n",
      "     |████████████████████████████████| 81 kB 1.9 MB/s             \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_eb273352e8de4640afacafaea51f8697/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_eb273352e8de4640afacafaea51f8697/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ikxn84q2\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysqlclient_eb273352e8de4640afacafaea51f8697/\n",
      "  Complete output (10 lines):\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_eb273352e8de4640afacafaea51f8697/setup.py\", line 17, in <module>\n",
      "      metadata, options = get_config()\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_eb273352e8de4640afacafaea51f8697/setup_posix.py\", line 44, in get_config\n",
      "      libs = mysql_config(\"libs_r\")\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_eb273352e8de4640afacafaea51f8697/setup_posix.py\", line 26, in mysql_config\n",
      "      raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "  OSError: mysql_config not found\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/db/f5/c8e1657985c31dda16e434edf5257c31572fa5faacd7e48b1618390e4b18/mysqlclient-1.3.9.tar.gz#sha256=990ccf1e1f15b9a291b811c993dc1c216566714bc14e6581b38665bd61c28c99 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.3.8.tar.gz (81 kB)\n",
      "     |████████████████████████████████| 81 kB 17.2 MB/s            \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_1ab61027a1ab4a66960ea513c203c4b6/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_1ab61027a1ab4a66960ea513c203c4b6/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_5yekyyu\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysqlclient_1ab61027a1ab4a66960ea513c203c4b6/\n",
      "  Complete output (10 lines):\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_1ab61027a1ab4a66960ea513c203c4b6/setup.py\", line 17, in <module>\n",
      "      metadata, options = get_config()\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_1ab61027a1ab4a66960ea513c203c4b6/setup_posix.py\", line 44, in get_config\n",
      "      libs = mysql_config(\"libs_r\")\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_1ab61027a1ab4a66960ea513c203c4b6/setup_posix.py\", line 26, in mysql_config\n",
      "      raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "  OSError: mysql_config not found\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/31/ce/7ea049b3d5929b3cce3104967ccca218a9f054517f0d15dfdaf4e76da2a0/mysqlclient-1.3.8.tar.gz#sha256=c64bc386c0b771ed6ff76de0f52e0f957f98d9e13c83b0ddb821afdbe3f5d970 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.3.7.tar.gz (79 kB)\n",
      "     |████████████████████████████████| 79 kB 14.2 MB/s            \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_e7e8084aca20458a9272c8df6e731889/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_e7e8084aca20458a9272c8df6e731889/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-z0o_gnj3\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysqlclient_e7e8084aca20458a9272c8df6e731889/\n",
      "  Complete output (10 lines):\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_e7e8084aca20458a9272c8df6e731889/setup.py\", line 17, in <module>\n",
      "      metadata, options = get_config()\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_e7e8084aca20458a9272c8df6e731889/setup_posix.py\", line 44, in get_config\n",
      "      libs = mysql_config(\"libs_r\")\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_e7e8084aca20458a9272c8df6e731889/setup_posix.py\", line 26, in mysql_config\n",
      "      raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "  OSError: mysql_config not found\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/74/ff/4e964e20b559e55d7afa60fbccc6a560f2adf289813bd3d7eb4eb8a87093/mysqlclient-1.3.7.tar.gz#sha256=c74a83b4cb2933d0e43370117eeebdfa03077ae72686d2df43d31879267f1f1b (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.3.6.tar.gz (78 kB)\n",
      "     |████████████████████████████████| 78 kB 7.1 MB/s             \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_9eab5d1039e44f35b0a178d8385e12f2/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_9eab5d1039e44f35b0a178d8385e12f2/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-im8wd4_1\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysqlclient_9eab5d1039e44f35b0a178d8385e12f2/\n",
      "  Complete output (10 lines):\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_9eab5d1039e44f35b0a178d8385e12f2/setup.py\", line 17, in <module>\n",
      "      metadata, options = get_config()\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_9eab5d1039e44f35b0a178d8385e12f2/setup_posix.py\", line 47, in get_config\n",
      "      libs = mysql_config(\"libs_r\")\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_9eab5d1039e44f35b0a178d8385e12f2/setup_posix.py\", line 29, in mysql_config\n",
      "      raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "  OSError: mysql_config not found\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/09/29/6648563af4b45798ba667f17ea55166d7b0ed8717937c06977a1fdbe7df6/mysqlclient-1.3.6.tar.gz#sha256=1f63a8ab111530a0ff9acaeb118074f11e7564b7c124f2e7fc56fcac641aecf2 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.3.5.tar.gz (77 kB)\n",
      "     |████████████████████████████████| 77 kB 5.7 MB/s             \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_198b6ea152a64deb93e7909585b7244f/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_198b6ea152a64deb93e7909585b7244f/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1h0u5u2l\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysqlclient_198b6ea152a64deb93e7909585b7244f/\n",
      "  Complete output (10 lines):\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_198b6ea152a64deb93e7909585b7244f/setup.py\", line 17, in <module>\n",
      "      metadata, options = get_config()\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_198b6ea152a64deb93e7909585b7244f/setup_posix.py\", line 47, in get_config\n",
      "      libs = mysql_config(\"libs_r\")\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_198b6ea152a64deb93e7909585b7244f/setup_posix.py\", line 29, in mysql_config\n",
      "      raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "  OSError: mysql_config not found\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/82/ea/336daf6c7baa564d0c434ab748218d1a7dc61dfc7066e98b72afd24fd2b9/mysqlclient-1.3.5.tar.gz#sha256=80ea68f6f3c2cfbf35c91adde2b40de1f2c31132118d2dcee048c72423f678bf (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.3.4.tar.gz (77 kB)\n",
      "     |████████████████████████████████| 77 kB 671 kB/s             \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_ff5de5a620d64d39aad68c422aec94b4/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_ff5de5a620d64d39aad68c422aec94b4/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-pyvir_ph\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysqlclient_ff5de5a620d64d39aad68c422aec94b4/\n",
      "  Complete output (10 lines):\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_ff5de5a620d64d39aad68c422aec94b4/setup.py\", line 17, in <module>\n",
      "      metadata, options = get_config()\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_ff5de5a620d64d39aad68c422aec94b4/setup_posix.py\", line 47, in get_config\n",
      "      libs = mysql_config(\"libs_r\")\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_ff5de5a620d64d39aad68c422aec94b4/setup_posix.py\", line 29, in mysql_config\n",
      "      raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "  OSError: mysql_config not found\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/17/d9/03b08e6a033401335b720806b87596aee8d7f7aa87539713238905c4a8d1/mysqlclient-1.3.4.tar.gz#sha256=a0263383f8ac33ad12d68dc61fa8ccbee41244ce916287c6cee71bf8aea82c5c (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.3.3.tar.gz (77 kB)\n",
      "     |████████████████████████████████| 77 kB 11.0 MB/s            \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_b8080b379e9340e5aa1bc8fc0bfb9c28/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_b8080b379e9340e5aa1bc8fc0bfb9c28/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-0hygbota\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysqlclient_b8080b379e9340e5aa1bc8fc0bfb9c28/\n",
      "  Complete output (10 lines):\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_b8080b379e9340e5aa1bc8fc0bfb9c28/setup.py\", line 17, in <module>\n",
      "      metadata, options = get_config()\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_b8080b379e9340e5aa1bc8fc0bfb9c28/setup_posix.py\", line 47, in get_config\n",
      "      libs = mysql_config(\"libs_r\")\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_b8080b379e9340e5aa1bc8fc0bfb9c28/setup_posix.py\", line 29, in mysql_config\n",
      "      raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "  OSError: mysql_config not found\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/26/53/c575db342bfca0213c9243ed2642bfadcd420b18d2f477dc812543e3d83a/mysqlclient-1.3.3.tar.gz#sha256=0f0887882d71bf2a079d9724d9323053cfbee8ab2dcfc989daf97d7ce5be9af9 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.3.2.tar.gz (77 kB)\n",
      "     |████████████████████████████████| 77 kB 10.5 MB/s            \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_a0369667a6c64945b812f644669fd0e1/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_a0369667a6c64945b812f644669fd0e1/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-5u10iez0\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysqlclient_a0369667a6c64945b812f644669fd0e1/\n",
      "  Complete output (10 lines):\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_a0369667a6c64945b812f644669fd0e1/setup.py\", line 17, in <module>\n",
      "      metadata, options = get_config()\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_a0369667a6c64945b812f644669fd0e1/setup_posix.py\", line 47, in get_config\n",
      "      libs = mysql_config(\"libs_r\")\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_a0369667a6c64945b812f644669fd0e1/setup_posix.py\", line 29, in mysql_config\n",
      "      raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "  OSError: mysql_config not found\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/2d/df/5440ee86bbb248325cdd6e1fc9cbbba365018a0d2d57f673610e020e6b1d/mysqlclient-1.3.2.tar.gz#sha256=e44025830501b9f70f8c2fe8eeff66f0df2df198802f7295801dac199b8236ef (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.3.1.tar.gz (76 kB)\n",
      "     |████████████████████████████████| 76 kB 989 kB/s             \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_1dc08ace7f9c488597a4d59d6f85ca97/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_1dc08ace7f9c488597a4d59d6f85ca97/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-9acch55o\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysqlclient_1dc08ace7f9c488597a4d59d6f85ca97/\n",
      "  Complete output (10 lines):\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_1dc08ace7f9c488597a4d59d6f85ca97/setup.py\", line 17, in <module>\n",
      "      metadata, options = get_config()\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_1dc08ace7f9c488597a4d59d6f85ca97/setup_posix.py\", line 47, in get_config\n",
      "      libs = mysql_config(\"libs_r\")\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_1dc08ace7f9c488597a4d59d6f85ca97/setup_posix.py\", line 29, in mysql_config\n",
      "      raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "  OSError: mysql_config not found\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/6b/ba/4729d99e85a0a35bb46d55500570de05b4af10431cef174b6da9f58a0e50/mysqlclient-1.3.1.tar.gz#sha256=3549e8a61f10c8cd8eac6581d3f44d0594f535fb7b29e6090db3a0bc547b25ad (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading mysqlclient-1.3.0.tar.gz (76 kB)\n",
      "     |████████████████████████████████| 76 kB 6.8 MB/s             \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_803e072814994041889df0a18f835097/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysqlclient_803e072814994041889df0a18f835097/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-e63gk7jh\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysqlclient_803e072814994041889df0a18f835097/\n",
      "  Complete output (10 lines):\n",
      "  /bin/sh: mysql_config: command not found\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_803e072814994041889df0a18f835097/setup.py\", line 17, in <module>\n",
      "      metadata, options = get_config()\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_803e072814994041889df0a18f835097/setup_posix.py\", line 47, in get_config\n",
      "      libs = mysql_config(\"libs_r\")\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysqlclient_803e072814994041889df0a18f835097/setup_posix.py\", line 29, in mysql_config\n",
      "      raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "  OSError: mysql_config not found\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/6a/91/bdfe808fb5dc99a5f65833b370818161b77ef6d1e19b488e4c146ab615aa/mysqlclient-1.3.0.tar.gz#sha256=06eb5664e3738b283ea2262ee60ed83192e898f019cc7ff251f4d05a564ab3b7 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25hCollecting mysql\n",
      "  Downloading mysql-0.0.2.tar.gz (1.9 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h  Downloading mysql-0.0.1.tar.gz (1.7 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hCollecting MySQL-python\n",
      "  Downloading MySQL-python-1.2.5.zip (108 kB)\n",
      "     |████████████████████████████████| 108 kB 76.3 MB/s            \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysql-python_576a4c04cf0d4cd3baebceb834cd1d5d/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysql-python_576a4c04cf0d4cd3baebceb834cd1d5d/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-wt__ueum\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysql-python_576a4c04cf0d4cd3baebceb834cd1d5d/\n",
      "  Complete output (7 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysql-python_576a4c04cf0d4cd3baebceb834cd1d5d/setup.py\", line 13, in <module>\n",
      "      from setup_posix import get_config\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysql-python_576a4c04cf0d4cd3baebceb834cd1d5d/setup_posix.py\", line 2, in <module>\n",
      "      from ConfigParser import SafeConfigParser\n",
      "  ModuleNotFoundError: No module named 'ConfigParser'\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/a5/e9/51b544da85a36a68debe7a7091f068d802fc515a3a202652828c73453cad/MySQL-python-1.2.5.zip#sha256=811040b647e5d5686f84db415efd697e6250008b112b6909ba77ac059e140c74 (from https://pypi.org/simple/mysql-python/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading MySQL-python-1.2.4.zip (113 kB)\n",
      "     |████████████████████████████████| 113 kB 48.4 MB/s            \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysql-python_16ece9d9ae874a178907ed34842cbcba/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysql-python_16ece9d9ae874a178907ed34842cbcba/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-k0xhhho0\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysql-python_16ece9d9ae874a178907ed34842cbcba/\n",
      "  Complete output (31 lines):\n",
      "  Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.28.tar.gz\n",
      "  Traceback (most recent call last):\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysql-python_16ece9d9ae874a178907ed34842cbcba/distribute_setup.py\", line 143, in use_setuptools\n",
      "      raise ImportError\n",
      "  ImportError\n",
      "  \n",
      "  During handling of the above exception, another exception occurred:\n",
      "  \n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysql-python_16ece9d9ae874a178907ed34842cbcba/setup.py\", line 7, in <module>\n",
      "      use_setuptools()\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysql-python_16ece9d9ae874a178907ed34842cbcba/distribute_setup.py\", line 145, in use_setuptools\n",
      "      return _do_download(version, download_base, to_dir, download_delay)\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysql-python_16ece9d9ae874a178907ed34842cbcba/distribute_setup.py\", line 124, in _do_download\n",
      "      to_dir, download_delay)\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysql-python_16ece9d9ae874a178907ed34842cbcba/distribute_setup.py\", line 194, in download_setuptools\n",
      "      src = urlopen(url)\n",
      "    File \"/home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/urllib/request.py\", line 223, in urlopen\n",
      "      return opener.open(url, data, timeout)\n",
      "    File \"/home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/urllib/request.py\", line 532, in open\n",
      "      response = meth(req, response)\n",
      "    File \"/home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/urllib/request.py\", line 642, in http_response\n",
      "      'http', request, response, code, msg, hdrs)\n",
      "    File \"/home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/urllib/request.py\", line 570, in error\n",
      "      return self._call_chain(*args)\n",
      "    File \"/home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n",
      "      result = func(*args)\n",
      "    File \"/home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/urllib/request.py\", line 650, in http_error_default\n",
      "      raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "  urllib.error.HTTPError: HTTP Error 403: SSL is required\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/90/5a/ce7bef80825c2188cf507baf57b37516e18dffdb198a6766a597f703059a/MySQL-python-1.2.4.zip#sha256=e405f9d6be33923d428acaa4db4f4470427f1d15ea0d2d82a933449ace26bbd9 (from https://pypi.org/simple/mysql-python/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Downloading MySQL-python-1.2.3.tar.gz (70 kB)\n",
      "     |████████████████████████████████| 70 kB 8.9 MB/s             \n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /home/ec2-user/anaconda3/envs/amazonei_tensorflow2_p36/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-mc68gd4b/mysql-python_9e47075b59f54d37ab9ad505578af0d6/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-mc68gd4b/mysql-python_9e47075b59f54d37ab9ad505578af0d6/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-u483hl8g\n",
      "       cwd: /tmp/pip-install-mc68gd4b/mysql-python_9e47075b59f54d37ab9ad505578af0d6/\n",
      "  Complete output (8 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysql-python_9e47075b59f54d37ab9ad505578af0d6/setup.py\", line 11, in <module>\n",
      "      from setup_posix import get_config\n",
      "    File \"/tmp/pip-install-mc68gd4b/mysql-python_9e47075b59f54d37ab9ad505578af0d6/setup_posix.py\", line 101\n",
      "      print \"\"\"You shouldn't be running this directly; it is used by setup.py.\"\"\"\n",
      "                                                                                ^\n",
      "  SyntaxError: Missing parentheses in call to 'print'. Did you mean print(\"\"\"You shouldn't be running this directly)?\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/9a/81/924d6799494cf7fb24370335c2f782088d6ac4f79e4137d4df94cea3582c/MySQL-python-1.2.3.tar.gz#sha256=7de66fbbf923634e7c965aeaefa74642ba75ae20ee1cefcefc3009595b7a7e6e (from https://pypi.org/simple/mysql-python/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25hINFO: pip is looking at multiple versions of boto3 to determine which version is compatible with other requirements. This could take a while.\n",
      "Collecting boto3\n",
      "  Using cached boto3-1.23.10-py3-none-any.whl (132 kB)\n",
      "INFO: pip is looking at multiple versions of pymysql to determine which version is compatible with other requirements. This could take a while.\n",
      "Collecting pymysql\n",
      "  Using cached PyMySQL-1.0.2-py3-none-any.whl (43 kB)\n",
      "INFO: pip is looking at multiple versions of mlflow to determine which version is compatible with other requirements. This could take a while.\n",
      "Collecting mlflow\n",
      "  Using cached mlflow-1.23.1-py3-none-any.whl (15.6 MB)\n",
      "\u001b[31mERROR: Cannot install mysql==0.0.1, mysql==0.0.2 and mysql==0.0.3 because these package versions have conflicting dependencies.\u001b[0m\n",
      "\n",
      "The conflict is caused by:\n",
      "    mysql 0.0.3 depends on mysqlclient\n",
      "    mysql 0.0.2 depends on mysqlclient\n",
      "    mysql 0.0.1 depends on MySQL-python\n",
      "\n",
      "To fix this you could try to:\n",
      "1. loosen the range of package versions you've specified\n",
      "2. remove package versions to allow pip attempt to solve the dependency conflict\n",
      "\n",
      "\u001b[31mERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "!pip install mlflow pymysql boto3 mysql"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "b29271ca",
   "metadata": {},
   "outputs": [
    {
     "ename": "OperationalError",
     "evalue": "(2003, \"Can't connect to MySQL server on 'mlflow-backend.chf6ry9cdkyl.eu-central-1.rds.amazonaws.com' (timed out)\")",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mtimeout\u001b[0m                                   Traceback (most recent call last)",
      "\u001b[0;32m~/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages/pymysql/connections.py\u001b[0m in \u001b[0;36mconnect\u001b[0;34m(self, sock)\u001b[0m\n\u001b[1;32m    613\u001b[0m                             sock = socket.create_connection(\n\u001b[0;32m--> 614\u001b[0;31m                                 \u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mhost\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mport\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mconnect_timeout\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    615\u001b[0m                             )\n",
      "\u001b[0;32m~/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/socket.py\u001b[0m in \u001b[0;36mcreate_connection\u001b[0;34m(address, timeout, source_address)\u001b[0m\n\u001b[1;32m    723\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0merr\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 724\u001b[0;31m         \u001b[0;32mraise\u001b[0m \u001b[0merr\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    725\u001b[0m     \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/socket.py\u001b[0m in \u001b[0;36mcreate_connection\u001b[0;34m(address, timeout, source_address)\u001b[0m\n\u001b[1;32m    712\u001b[0m                 \u001b[0msock\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbind\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msource_address\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 713\u001b[0;31m             \u001b[0msock\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mconnect\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msa\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    714\u001b[0m             \u001b[0;31m# Break explicitly a reference cycle\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mtimeout\u001b[0m: timed out",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mOperationalError\u001b[0m                          Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-10-dfa8e7eec340>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     17\u001b[0m                              \u001b[0mport\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m3306\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     18\u001b[0m                              \u001b[0mcursorclass\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mpymysql\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcursors\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mDictCursor\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 19\u001b[0;31m                              connect_timeout=5)\n\u001b[0m\u001b[1;32m     20\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     21\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages/pymysql/connections.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, user, password, host, database, unix_socket, port, charset, sql_mode, read_default_file, conv, use_unicode, client_flag, cursorclass, init_command, connect_timeout, read_default_group, autocommit, local_infile, max_allowed_packet, defer_connect, auth_plugin_map, read_timeout, write_timeout, bind_address, binary_prefix, program_name, server_public_key, ssl, ssl_ca, ssl_cert, ssl_disabled, ssl_key, ssl_verify_cert, ssl_verify_identity, compress, named_pipe, passwd, db)\u001b[0m\n\u001b[1;32m    351\u001b[0m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_sock\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    352\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 353\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mconnect\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    354\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    355\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m__enter__\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/amazonei_tensorflow2_p36/lib/python3.6/site-packages/pymysql/connections.py\u001b[0m in \u001b[0;36mconnect\u001b[0;34m(self, sock)\u001b[0m\n\u001b[1;32m    662\u001b[0m                 \u001b[0;32mif\u001b[0m \u001b[0mDEBUG\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    663\u001b[0m                     \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mexc\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtraceback\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 664\u001b[0;31m                 \u001b[0;32mraise\u001b[0m \u001b[0mexc\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    665\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    666\u001b[0m             \u001b[0;31m# If e is neither DatabaseError or IOError, It's a bug.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mOperationalError\u001b[0m: (2003, \"Can't connect to MySQL server on 'mlflow-backend.chf6ry9cdkyl.eu-central-1.rds.amazonaws.com' (timed out)\")"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.metrics import mean_squared_error\n",
    "from sklearn.linear_model import LinearRegression\n",
    "import mlflow\n",
    "import mlflow.sklearn\n",
    "\n",
    "import pymysql\n",
    "\n",
    "# Connect to the database\n",
    "connection = pymysql.connect(host='mlflow-backend.chf6ry9cdkyl.eu-central-1.rds.amazonaws.com',\n",
    "                             user='admin',\n",
    "                             password='mlflowadmin',\n",
    "                             database='mlflow-backend',\n",
    "                             charset='utf8mb4',\n",
    "                             port=3306,\n",
    "                             cursorclass=pymysql.cursors.DictCursor,\n",
    "                             connect_timeout=5)\n",
    "\n",
    "\n",
    "X = np.linspace(0, 1, 11)\n",
    "y = X*2\n",
    "X = np.array([[x] for x in X])\n",
    "y = np.array([[i] for i in y])\n",
    "\n",
    "s3_bucket = \"s3://mi4people-soil-project/mlflow-artifacts/\"\n",
    "mlflow.create_experiment(\"test4\", s3_bucket)\n",
    "mlflow.set_experiment('test4')\n",
    "mlflow.sklearn.autolog()\n",
    "mlflow.set_tracking_uri(\"s3://mi4people-soil-project/mlflow-artifacts/\")\n",
    "mlflow.set_registry_uri(\"s3://mi4people-soil-project/mlflow-backend/\")\n",
    "with mlflow.start_run():\n",
    "    model = LinearRegression()\n",
    "    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)\n",
    "    model.fit(X_train, y_train)\n",
    "    y_pred = model.predict(X_test)\n",
    "    mse = sum([np.sqrt((i-j)**2) for i, j in  zip(y_pred, y_test)])\n",
    "    #mlflow.log_metric(\"mse\", mse)\n",
    "    #mlflow.log_artifact(model)\n",
    "# TODO parse mlruns and write to s3? Or set up tracking server?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "8c3594b2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting package metadata (current_repodata.json): done\n",
      "Solving environment: | ^C\n",
      "failed with initial frozen solve. Retrying with flexible solve.\n"
     ]
    }
   ],
   "source": [
    "!conda install mysql"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "9fbb3ce7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/home/ec2-user/SageMaker/MI4People_soil_quality/notebooks/utils\n"
     ]
    }
   ],
   "source": [
    "!pwd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "909952d1",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pymysql\n",
    "import mysql.connector\n",
    "import sys\n",
    "import boto3\n",
    "import os\n",
    "\n",
    "ENDPOINT='mlflow-backend.chf6ry9cdkyl.eu-central-1.rds.amazonaws.com'\n",
    "PORT=\"3306\"\n",
    "USER=\"admin\"\n",
    "REGION=\"eu-central-1c\"\n",
    "DBNAME=\"mlflow-backend\"\n",
    "os.environ['LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN'] = '1'\n",
    "\n",
    "#gets the credentials from .aws/credentials\n",
    "session = boto3.Session(profile_name='default')\n",
    "client = session.client('rds')\n",
    "\n",
    "token = client.generate_db_auth_token(DBHostname=ENDPOINT, Port=PORT, DBUsername=USER, Region=REGION)\n",
    "\n",
    "try:\n",
    "    conn =  mysql.connector.connect(host=ENDPOINT, user=USER, passwd=token, port=PORT, database=DBNAME, ssl_ca='SSLCERTIFICATE')\n",
    "    cur = conn.cursor()\n",
    "    cur.execute(\"\"\"SELECT now()\"\"\")\n",
    "    query_results = cur.fetchall()\n",
    "    print(query_results)\n",
    "except Exception as e:\n",
    "    print(\"Database connection failed due to {}\".format(e))          \n",
    "                "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "conda_amazonei_tensorflow2_p36",
   "language": "python",
   "name": "conda_amazonei_tensorflow2_p36"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
